wandb_version: 1

current_time:
  desc: null
  value: 25-11-26-09-16-14
name_str:
  desc: null
  value: ''
env_list:
  desc: null
  value: HalfCheetah-v2
data_source:
  desc: null
  value: medium_replay
unreal_dynamics:
  desc: null
  value: gravity
variety_list:
  desc: null
  value: '2.0'
replaybuffer_ratio:
  desc: null
  value: 10.0
real_residual_ratio:
  desc: null
  value: 1.0
tanh_scale:
  desc: null
  value: 2
dis_dropout:
  desc: null
  value: false
warmup_steps:
  desc: null
  value: 0
max_traj_length:
  desc: null
  value: 1000
seed:
  desc: null
  value: 42
device:
  desc: null
  value: cuda
save_model:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
reward_scale:
  desc: null
  value: 1.0
reward_bias:
  desc: null
  value: 0.0
clip_action:
  desc: null
  value: 1.0
joint_noise_std:
  desc: null
  value: 0.0
policy_arch:
  desc: null
  value: 256-256
qf_arch:
  desc: null
  value: 256-256
orthogonal_init:
  desc: null
  value: false
policy_log_std_multiplier:
  desc: null
  value: 1.0
policy_log_std_offset:
  desc: null
  value: -1.0
dynamics_model:
  desc: null
  value: false
model_train_epoch:
  desc: null
  value: 10000
model_lr:
  desc: null
  value: 0.0003
model_dropout:
  desc: null
  value: false
n_epochs:
  desc: null
  value: 1000
bc_epochs:
  desc: null
  value: 0
n_rollout_steps_per_epoch:
  desc: null
  value: 1000
n_train_step_per_epoch:
  desc: null
  value: 1000
eval_period:
  desc: null
  value: 10
eval_n_trajs:
  desc: null
  value: 5
h2o.alpha_multiplier:
  desc: null
  value: 1.0
h2o.automatic_exploit_coeff_tuning:
  desc: null
  value: false
h2o.backup_dynamics_entropy:
  desc: null
  value: false
h2o.backup_policy_entropy:
  desc: null
  value: true
h2o.batch_sim_ratio:
  desc: null
  value: 0.5
h2o.batch_size:
  desc: null
  value: 256
h2o.clip_dynamics_ratio_max:
  desc: null
  value: 1
h2o.clip_dynamics_ratio_min:
  desc: null
  value: 1.0e-05
h2o.d_sa_lr:
  desc: null
  value: 0.0003
h2o.d_sas_lr:
  desc: null
  value: 0.0003
h2o.device:
  desc: null
  value: cuda
h2o.discount:
  desc: null
  value: 0.99
h2o.dynamics_ratio_lr:
  desc: null
  value: 0.0003
h2o.exploit_coeff:
  desc: null
  value: 0.5
h2o.f:
  desc: null
  value: algae
h2o.in_sample:
  desc: null
  value: true
h2o.noise_std_discriminator:
  desc: null
  value: 0.1
h2o.optimizer_type:
  desc: null
  value: adam
h2o.policy_lr:
  desc: null
  value: 0.0003
h2o.qf_lr:
  desc: null
  value: 0.0003
h2o.quantile:
  desc: null
  value: 0.5
h2o.sampling_n_next_states:
  desc: null
  value: 10
h2o.soft_target_update_rate:
  desc: null
  value: 0.005
h2o.sparse_alpha:
  desc: null
  value: 1.0
h2o.target_entropy:
  desc: null
  value: 0.0
h2o.target_update_period:
  desc: null
  value: 1
h2o.temperature:
  desc: null
  value: 1
h2o.use_automatic_entropy_tuning:
  desc: null
  value: true
h2o.use_quantile_regression:
  desc: null
  value: true
h2o.use_real_blended_target:
  desc: null
  value: true
h2o.use_sim_blended_target:
  desc: null
  value: true
h2o.use_td_target_ratio:
  desc: null
  value: true
h2o.vf_lr:
  desc: null
  value: 0.0003
logging.anonymous:
  desc: null
  value: null
logging.entity:
  desc: null
  value: null
logging.experiment_id:
  desc: null
  value: null
logging.notes:
  desc: null
  value: null
logging.online:
  desc: null
  value: true
logging.output_dir:
  desc: null
  value: ./experiment_output
logging.prefix:
  desc: null
  value: ''
logging.project:
  desc: null
  value: H2O+
logging.random_delay:
  desc: null
  value: 0.0
hostname:
  desc: null
  value: FATHERSUCKERMSI
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1764119776.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 14
      - 16
      - 17
      - 23
      - 37
      4: 3.7.12
      5: 0.16.6
      8:
      - 8
      13: linux-x86_64
