_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.7.12
            "5": 0.18.7
            "8":
                - 8
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 256
bc_epochs:
    value: 0
clip_action:
    value: 1
current_time:
    value: 25-11-26-09-28-33
data_source:
    value: medium_replay
device:
    value: cuda
dis_dropout:
    value: false
dynamics_model:
    value: false
env_list:
    value: HalfCheetah-v2
eval_n_trajs:
    value: 5
eval_period:
    value: 10
h2o.alpha_multiplier:
    value: 1
h2o.automatic_exploit_coeff_tuning:
    value: false
h2o.backup_dynamics_entropy:
    value: false
h2o.backup_policy_entropy:
    value: true
h2o.batch_sim_ratio:
    value: 0.5
h2o.batch_size:
    value: 256
h2o.clip_dynamics_ratio_max:
    value: 1
h2o.clip_dynamics_ratio_min:
    value: 1e-05
h2o.d_sa_lr:
    value: 0.0003
h2o.d_sas_lr:
    value: 0.0003
h2o.device:
    value: cuda
h2o.discount:
    value: 0.99
h2o.dynamics_ratio_lr:
    value: 0.0003
h2o.exploit_coeff:
    value: 0.5
h2o.f:
    value: algae
h2o.in_sample:
    value: true
h2o.noise_std_discriminator:
    value: 0.1
h2o.optimizer_type:
    value: adam
h2o.policy_lr:
    value: 0.0003
h2o.qf_lr:
    value: 0.0003
h2o.quantile:
    value: 0.5
h2o.sampling_n_next_states:
    value: 10
h2o.soft_target_update_rate:
    value: 0.005
h2o.sparse_alpha:
    value: 1
h2o.target_entropy:
    value: 0
h2o.target_update_period:
    value: 1
h2o.temperature:
    value: 1
h2o.use_automatic_entropy_tuning:
    value: true
h2o.use_quantile_regression:
    value: true
h2o.use_real_blended_target:
    value: true
h2o.use_sim_blended_target:
    value: true
h2o.use_td_target_ratio:
    value: true
h2o.vf_lr:
    value: 0.0003
hostname:
    value: FATHERSUCKERMSI
joint_noise_std:
    value: 0
logging.anonymous:
    value: null
logging.entity:
    value: null
logging.experiment_id:
    value: null
logging.notes:
    value: null
logging.online:
    value: true
logging.output_dir:
    value: ./experiment_output
logging.prefix:
    value: ""
logging.project:
    value: H2O+
logging.random_delay:
    value: 0
max_traj_length:
    value: 1000
model_dropout:
    value: false
model_lr:
    value: 0.0003
model_train_epoch:
    value: 10000
n_epochs:
    value: 1000
n_rollout_steps_per_epoch:
    value: 1000
n_train_step_per_epoch:
    value: 1000
name_str:
    value: ""
orthogonal_init:
    value: false
policy_arch:
    value: 256-256
policy_log_std_multiplier:
    value: 1
policy_log_std_offset:
    value: -1
qf_arch:
    value: 256-256
real_residual_ratio:
    value: 1
replaybuffer_ratio:
    value: 10
reward_bias:
    value: 0
reward_scale:
    value: 1
save_model:
    value: false
seed:
    value: 42
tanh_scale:
    value: 2
unreal_dynamics:
    value: gravity
variety_list:
    value: "2.0"
warmup_steps:
    value: 0
