"""
rebuild_z_from_snapshots.py
===========================
Post-process HDF5 datasets to rebuild z_t/z_t1 from stored snapshot_T1.

Problem: collect_worker used bridge_to_snapshot() which includes ALL 12 SUMO
bus lines (~83 buses), while BusSimEnv only simulates 7X (~3-15 buses).
This caused 200x density mismatch in z features, making the discriminator
trivially separate real from sim data.

Fix: snapshot_T1 in the h5 files was generated by bridge_to_full_snapshot()
which is already filtered to 7X only. We rebuild z_t from these snapshots.

For z_t1 (arrival time): we use the snapshot_T1 of the next transition
(in temporal order), which is a reasonable proxy for the network state
at the arrival event.

Usage:
    python rebuild_z_from_snapshots.py [--dataset_dir datasets] [--dry_run]
"""

import argparse
import glob
import os
import pickle
import sys
import time

import h5py
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

from common.data_utils import extract_structured_context, set_route_length

ROUTE_LENGTH = 13149.8  # consistent with h2o+_bus_main.py


def rebuild_one_file(fpath: str, dry_run: bool = False, zero_waiting: bool = True):
    """Rebuild z_t and z_t1 for a single h5 file."""
    basename = os.path.basename(fpath)
    print(f"\n[rebuild] Processing {basename} ...")

    with h5py.File(fpath, "r") as f:
        N = f["observations"].shape[0]
        sim_times = np.array(f["sim_time"])          # (N,)
        old_zt = np.array(f["z_t"])
        old_zt1 = np.array(f["z_t1"])

        # Load snapshots — supports both formats:
        #   v1: snapshot_T1 (N, max_len) uint8 + snapshot_T1_lens (N,) int64
        #   v2: snapshot_T1 vlen_dtype(uint8) — each entry is variable-length
        snap_ds = f["snapshot_T1"]
        if "snapshot_T1_lens" in f:
            # v1 fixed-size format
            snap_arr = np.array(snap_ds)       # (N, max_len) uint8
            snap_lens = np.array(f["snapshot_T1_lens"])  # (N,) int64
            snap_bytes_list = [bytes(snap_arr[i, :int(snap_lens[i])]) for i in range(N)]
        else:
            # v2 vlen format: each entry is a variable-length uint8 array
            snap_bytes_list = [bytes(snap_ds[i]) for i in range(N)]

    print(f"  {N} transitions, snapshot format={'v1' if 'snap_lens' in dir() else 'v2(vlen)'}")

    # Pre-stats
    print(f"  OLD z_t  density[10:20] mean={old_zt[:, 10:20].mean():.4f}, "
          f"waiting[20:30] mean={old_zt[:, 20:30].mean():.4f}")
    print(f"  OLD z_t1 density[10:20] mean={old_zt1[:, 10:20].mean():.4f}, "
          f"waiting[20:30] mean={old_zt1[:, 20:30].mean():.4f}")

    # Rebuild z_t from snapshot_T1
    set_route_length(ROUTE_LENGTH)
    new_zt = np.zeros((N, 30), dtype=np.float32)
    failed = 0

    t0 = time.time()
    for i in range(N):
        snap_b = snap_bytes_list[i]
        if not snap_b:
            failed += 1
            continue
        try:
            snap = pickle.loads(snap_b)
            z = extract_structured_context(snap)
            if zero_waiting:
                z[20:30] = 0.0  # Zero out waiting (unreliable in SUMO data)
            new_zt[i] = z
        except Exception as e:
            failed += 1
            if failed <= 3:
                print(f"    WARN: failed to rebuild z_t[{i}]: {e}")

    # Rebuild z_t1: use next transition's snapshot_T1 as proxy
    # Sort by sim_time to get temporal ordering
    time_order = np.argsort(sim_times)
    new_zt1 = np.zeros((N, 30), dtype=np.float32)

    for rank in range(len(time_order)):
        idx = time_order[rank]
        # Use next transition's z as z_t1
        if rank + 1 < len(time_order):
            next_idx = time_order[rank + 1]
            new_zt1[idx] = new_zt[next_idx]
        else:
            # Last transition: use own z
            new_zt1[idx] = new_zt[idx]

    elapsed = time.time() - t0
    print(f"  Rebuilt {N - failed}/{N} z vectors ({failed} failed) in {elapsed:.1f}s")
    print(f"  NEW z_t  density[10:20] mean={new_zt[:, 10:20].mean():.4f}, "
          f"waiting[20:30] mean={new_zt[:, 20:30].mean():.4f}")
    print(f"  NEW z_t1 density[10:20] mean={new_zt1[:, 10:20].mean():.4f}, "
          f"waiting[20:30] mean={new_zt1[:, 20:30].mean():.4f}")

    if dry_run:
        print(f"  [DRY RUN] Skipping write.")
        return

    # Backup old z and write new
    backup_path = fpath + ".z_backup"
    if not os.path.exists(backup_path):
        with h5py.File(backup_path, "w") as fb:
            fb.create_dataset("z_t_old", data=old_zt, compression="gzip")
            fb.create_dataset("z_t1_old", data=old_zt1, compression="gzip")
        print(f"  Backed up old z to {os.path.basename(backup_path)}")

    with h5py.File(fpath, "a") as f:
        del f["z_t"]
        del f["z_t1"]
        f.create_dataset("z_t", data=new_zt, compression="gzip")
        f.create_dataset("z_t1", data=new_zt1, compression="gzip")
    print(f"  ✅ Written new z_t/z_t1 to {basename}")


def main():
    parser = argparse.ArgumentParser(description="Rebuild z features from snapshot_T1")
    parser.add_argument("--dataset_dir", default=os.path.join(_HERE, "datasets"))
    parser.add_argument("--glob", default="sumo_*.h5")
    parser.add_argument("--dry_run", action="store_true", help="Don't write, just preview")
    parser.add_argument("--zero_waiting", action="store_true", default=True,
                        help="Zero out waiting channel (default: True)")
    args = parser.parse_args()

    files = sorted(glob.glob(os.path.join(args.dataset_dir, args.glob)))
    if not files:
        print(f"No files matching {args.glob} in {args.dataset_dir}")
        return

    print(f"[rebuild] Found {len(files)} files, route_length={ROUTE_LENGTH}")
    for fpath in files:
        rebuild_one_file(fpath, dry_run=args.dry_run, zero_waiting=args.zero_waiting)

    print(f"\n[rebuild] Done! Processed {len(files)} files.")


if __name__ == "__main__":
    main()
